target_versions:
  - 3.3.3
  - 3.4.0
  - 3.4.1
  - 3.4.2
  - 3.4.3
  - 3.4.4
  - 3.5.0
  - 3.5.1
  - 3.5.2
  - 3.5.3
  - 3.6.0
  - 3.6.1
  - 3.6.2
  - 3.6.3
  - 4.0.0
  - 4.0.1
  - 4.0.2
  - 4.0.3
  - 4.0.4
  - 4.0.5
  - 4.1.0
  - 4.1.1
  - 4.1.2
  - 4.1.3
  - 4.2.0
  - 4.2.1
  - 4.2.2
  - 4.2.3
  - 4.3.0
  - 4.3.1
target_repos:
  # repo name and target branch
  - swirl: staging
  - swirlify: staging
  - DataScienceAndR: dev/course
repos_dir: 'repos'
docker_dir: 'docker'
tests:
  - name: DataScienceAndR
    test_course: DataScienceAndR
    lesson_prefix:
      - 00-Hello-DataScienceAndR
      - 01-RBasic-01-Introduction
      - 01-RBasic-02-Data-Structure-Vectors
      - 01-RBasic-03-Data-Structure-Object
      - 01-RBasic-04-Factors
      - 01-RBasic-05-Arrays-Matrices
      - 01-RBasic-06-List-DataFrame
      - 01-RBasic-07-Loading-Dataset
      - 02-RDataEngineer-01-Parsing
      - 02-RDataEngineer-02-XML
      - 02-RDataEngineer-03-JSON
      - 02-RDataEngineer-04-Database
      - 02-RDataEngineer-05-Data-Manipulation
      - 02-RDataEngineer-06-Join
      - 03-RVisualization-01-One-Variable-Visualization
      - 03-RVisualization-02-Multiple-Variables-Visualization
      - 03-RVisualization-03-ggplot2
      - 03-RVisualization-04-Javascript-And-Maps
      - Optional-RProgramming-01-Loop-And-Condition
      - Optional-RProgramming-02-Function-Introduction
      - Project-ROpenData-Power-GDP
use_cache_r_lib: false
checkout_target_repos: true
